<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'csvbackend' => '/CsvBackend.php',
                'email' => '/Email.php',
                'getrequest' => '/GetRequest.php',
                'invalidemailexception' => '/InvalidEmailException.php',
                'invalidphonenumberexception' => '/InvalidPhoneNumberException.php',
                'phonenumber' => '/PhoneNumber.php',
                'postrequest' => '/PostRequest.php',
                'request' => '/Request.php',
                'sportticketsformcommand' => '/SportTicketsFormCommand.php',
                'xslrenderer' => '/XslRenderer.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
